In [222]:
import pandas as pd
from datetime import datetime
import re

In [290]:
df = pd.read_csv("Podatek dochodowy od osób prawnych!.csv")

In [ ]:
df.head()

In [291]:
df.shape

(976, 17)

In [ ]:
df.describe()

In [ ]:
df['nazwa'].value_counts()

In [ ]:
df['Data_orzeczenia'].value_counts()

In [ ]:
df['Sędziowie'].value_counts()

In [ ]:
df['Sąd'].value_counts()

In [ ]:
df['Treść_wyniku'].value_counts()

# uchylono - pozytywny wynik
# oddalono - negatywny wynik

In [ ]:
df.plot.hist()

In [13]:
df.groupby('Sąd')

In [157]:
df.head()

,Unnamed: 0,nazwa,Data orzeczenia,Data wpływu,Sąd,Sędziowie,Symbol z opisem,Hasła tematyczne,Skarżony organ,Treść wyniku,Powołane przepisy,Sygn. powiązane,Publikacja w u.z.o.,Info.o glosach,SENTENCJA,UZASADNIENIE,TEZY
0,0,I SA/Wr 567/22 - Wyrok WSA we Wrocławiu,2023-07-27 orzeczenie nieprawomocne,2022-08-25,Wojewódzki Sąd Administracyjny we Wrocławiu,Dagmara Stankiewicz-Rajchman\nIwona Solatycka\...,6113 Podatek dochodowy od osób prawnych\n6560,Interpretacje podatkowe\nPodatek dochodowy od ...,Dyrektor Krajowej Informacji Skarbowej,*Oddalono skargę w całości,Dz.U. 2021 poz 1800 art. 15 ust. 2a\nUstawa z ...,-,-,-,Wojewódzki Sąd Administracyjny we Wrocławiu w ...,-,-
1,1,I SA/Gd 491/23 - Wyrok WSA w Gdańsku,2023-07-25 orzeczenie nieprawomocne,2023-05-26,Wojewódzki Sąd Administracyjny w Gdańsku,Alicja Stępień /sprawozdawca/\nMałgorzata Gorz...,6113 Podatek dochodowy od osób prawnych\n6560,Podatek dochodowy od osób prawnych,Dyrektor Krajowej Informacji Skarbowej,Oddalono skargę,"Dz.U. 2021 poz 1800 art. 28m ust. 1 pkt 2 i 3,...",-,-,-,Wojewódzki Sąd Administracyjny w Gdańsku w skł...,Dnia 16 lutego 2023 r. wpłynął wniosek B. Sp. ...,-
2,2,I SA/Gl 1521/22 - Wyrok WSA w Gliwicach,2023-07-19 orzeczenie nieprawomocne,2022-11-28,Wojewódzki Sąd Administracyjny w Gliwicach,Borys Marasek\nDorota Kozłowska /przewodnicząc...,6113 Podatek dochodowy od osób prawnych\n6560,Podatek dochodowy od osób prawnych,Dyrektor Krajowej Informacji Skarbowej,Oddalono skargę,Dz.U. 2021 poz 1540 art. 22 par. 1\nUstawa z d...,-,-,-,Wojewódzki Sąd Administracyjny w Gliwicach w s...,-,-
3,3,I SA/Lu 270/23 - Wyrok WSA w Lublinie,2023-07-12 orzeczenie nieprawomocne,2023-04-28,Wojewódzki Sąd Administracyjny w Lublinie,Grzegorz Wałejko\nHalina Chitrosz-Roicka /prze...,6113 Podatek dochodowy od osób prawnych,Podatek dochodowy od osób prawnych,Naczelnik Urzędu Skarbowego,Oddalono skargę,Dz.U. 2021 poz 1800 art. 26b ust. 3\nUstawa z ...,-,-,-,Wojewódzki Sąd Administracyjny w Lublinie w sk...,-,-
4,4,I SA/Gl 119/23 - Wyrok WSA w Gliwicach,2023-07-12 orzeczenie nieprawomocne,2023-01-23,Wojewódzki Sąd Administracyjny w Gliwicach,Dorota Kozłowska\nMonika Krywow\nPaweł Kornack...,6113 Podatek dochodowy od osób prawnych\n6560,Interpretacje podatkowe\nPodatek dochodowy od ...,Dyrektor Krajowej Informacji Skarbowej,Uchylono zaskarżoną interpretację indywidualną,Dz.U. 2022 poz 2587 art. 38eb ust. 3\nUstawa z...,-,-,-,Wojewódzki Sąd Administracyjny w Gliwicach w s...,1. G sp. z o.o. w D. wniosła skargę na interpr...,-

In [292]:

def prawomocność_func(x):
    if x == "nieprawomocne":
        return 0
    elif x == "prawomocne":
        return 1
    else:
        return "None"

    
def wynik_func(x):
    # uchylono - pozytywny wynik
    # oddalono - negatywny wynik
    if "uchylono" in x.lower() or "uchyla" in x.lower():
        return 1
    elif "oddalono" in x.lower() or "oddalonno" in x.lower():
        return 0
    else:
        return "None"



def miesiac_func(x):
    return datetime.strptime(x, '%Y-%m-%d').date().month

def dzien_tygodnia_func(x):
    return datetime.strptime(x, '%Y-%m-%d').date().weekday()



def sędzia_func(x):
    if isinstance(x,str):
        return re.split(" /", x)[0]
    else:
        return "None"

    

# renaming
df = df.rename(columns = {'Data orzeczenia':'Data_orzeczenia'})
df = df.rename(columns = {'Data wpływu':'Data_wpływu'})
df = df.rename(columns = {'Symbol z opisem':'Symbol_z_opisem'})
df = df.rename(columns = {'Hasła tematyczne':'Hasła_tematyczne'})
df = df.rename(columns = {'Skarżony organ':'Skarżony_organ'})
df = df.rename(columns = {'Treść wyniku':'Treść_wyniku'})

# Adding two new columns to the existing dataframe.
# bydefault splitting is done on the basis of single space.
df[['Data_orzeczenia','orz',"Prawomocność"]] = df.Data_orzeczenia.str.split(expand=True)

#selecting relevant columns
df = df[['Data_orzeczenia', 'Sąd', 'Sędziowie', 'Treść_wyniku', 'Prawomocność']]


#applying functions
df['Prawomocność'] = df['Prawomocność'].apply(prawomocność_func)
df["Treść_wyniku"] = df["Treść_wyniku"].apply(wynik_func)

df["Miesiąc_orzeczenia"] = df["Data_orzeczenia"].apply(miesiac_func)
df["Dzien_tygodnia_orzeczenia"] = df["Data_orzeczenia"].apply(dzien_tygodnia_func)


# 
df = df.join(df['Sędziowie'].str.split('\n',expand=True).add_prefix('name_'))

df["name_0"] = df["name_0"].apply(sędzia_func)
df["name_1"] = df["name_1"].apply(sędzia_func)
df["name_2"] = df["name_2"].apply(sędzia_func)
df

,Data_orzeczenia,Sąd,Sędziowie,Treść_wyniku,Prawomocność,Miesiąc_orzeczenia,Dzien_tygodnia_orzeczenia,name_0,name_1,name_2
0,2023-07-27,Wojewódzki Sąd Administracyjny we Wrocławiu,Dagmara Stankiewicz-Rajchman\nIwona Solatycka\...,0,0,7,3,Dagmara Stankiewicz-Rajchman,Iwona Solatycka,Tadeusz Haberka
1,2023-07-26,Wojewódzki Sąd Administracyjny w Lublinie,Grzegorz Wałejko\nHalina Chitrosz-Roicka /prze...,0,0,7,2,Grzegorz Wałejko,Halina Chitrosz-Roicka,Monika Kazubińska-Kręcisz
2,2023-07-25,Wojewódzki Sąd Administracyjny w Gdańsku,Alicja Stępień /sprawozdawca/\nMałgorzata Gorz...,0,0,7,1,Alicja Stępień,Małgorzata Gorzeń,Marek Kraus
3,2023-07-24,Wojewódzki Sąd Administracyjny w Gliwicach,Beata Machcińska /przewodniczący sprawozdawca/,1,0,7,0,Beata Machcińska,None,None
4,2023-07-19,Wojewódzki Sąd Administracyjny w Gliwicach,Borys Marasek\nDorota Kozłowska /przewodnicząc...,0,0,7,2,Borys Marasek,Dorota Kozłowska,Monika Krywow
...,...,...,...,...,...,...,...,...,...,...
971,2022-06-07,Wojewódzki Sąd Administracyjny w Poznaniu,Karol Pawlicki /sprawozdawca/\nKatarzyna Nikod...,0,0,6,1,Karol Pawlicki,Katarzyna Nikodem,Waldemar Inerowicz
972,2022-06-07,Wojewódzki Sąd Administracyjny w Poznaniu,Karol Pawlicki /sprawozdawca/\nKatarzyna Nikod...,0,0,6,1,Karol Pawlicki,Katarzyna Nikodem,Waldemar Inerowicz
973,2022-06-07,Wojewódzki Sąd Administracyjny w Poznaniu,Karol Pawlicki /sprawozdawca/\nKatarzyna Nikod...,0,0,6,1,Karol Pawlicki,Katarzyna Nikodem,Waldemar Inerowicz
974,2022-06-07,Wojewódzki Sąd Administracyjny w Poznaniu,Karol Pawlicki\nKatarzyna Nikodem /sprawozdawc...,0,0,6,1,Karol Pawlicki,Katarzyna Nikodem,Waldemar Inerowicz
975,2022-06-07,Wojewódzki Sąd Administracyjny w Poznaniu,Karol Pawlicki\nKatarzyna Nikodem /sprawozdawc...,0,0,6,1,Karol Pawlicki,Katarzyna Nikodem,Waldemar Inerowicz

In [180]:
df[['Sąd', 'Treść_wyniku', 'Prawomocność']].groupby('Sąd').mean().round(2)

                                                 Treść_wyniku  Prawomocność
Sąd
Naczelny Sąd Administracyjny                             0.21          1.00
Wojewódzki Sąd Administracyjny w Białymstoku             0.35          0.12
Wojewódzki Sąd Administracyjny w Bydgoszczy              0.35          0.30
Wojewódzki Sąd Administracyjny w Gdańsku                 0.52          0.26
Wojewódzki Sąd Administracyjny w Gliwicach               0.68          0.15
Wojewódzki Sąd Administracyjny w Gorzowie Wlkp.          0.50          0.19
Wojewódzki Sąd Administracyjny w Kielcach                0.40          0.40
Wojewódzki Sąd Administracyjny w Krakowie                0.70          0.10
Wojewódzki Sąd Administracyjny w Lublinie                0.27          0.29
Wojewódzki Sąd Administracyjny w Olsztynie               0.67          0.22
Wojewódzki Sąd Administracyjny w Opolu                   0.77          0.23
Wojewódzki Sąd Administracyjny w Poznaniu                0.64          0.11
Wojewódzki Sąd Administracyjny w Rzeszowie               0.68          0.18
Wojewódzki Sąd Administracyjny w Szczecinie              0.56          0.44
Wojewódzki Sąd Administracyjny w Warszawie               0.57          0.23
Wojewódzki Sąd Administracyjny w Łodzi                   0.57          0.14
Wojewódzki Sąd Administracyjny we Wrocławiu              0.67          0.19

In [181]:
df[['Sędziowie', 'Treść_wyniku', 'Prawomocność']].groupby('Sędziowie').mean().round(2)

                                                    Treść_wyniku  Prawomocność
Sędziowie
Adam Jutrzenka-Trzebiatowski\nDamian Bronowicki...          1.00          1.00
Adrianna Elżbieta Grzymska-Truksa\nAgnieszka Ba...          1.00          0.00
Adrianna Elżbieta Grzymska-Truksa\nAgnieszka Ba...          0.00          1.00
Adrianna Elżbieta Grzymska-Truksa\nDariusz Czar...          1.00          0.00
Adrianna Elżbieta Grzymska-Truksa\nDariusz Czar...          0.75          0.00
...                                                          ...           ...
Tomasz Smoleń /przewodniczący sprawozdawca/                 1.00          0.00
Waldemar Inerowicz /przewodniczący sprawozdawca/            0.50          0.25
Waldemar Michaldo /przewodniczący sprawozdawca/             1.00          0.00
Wiesław Kuśnierz /przewodniczący sprawozdawca/              1.00          0.00
Łukasz Cieślak\nMarta Semiczek /sprawozdawca/\n...          1.00          0.00

[631 rows x 2 columns]

In [103]:
def miesiac_func(x):
    return datetime.strptime(x, '%Y-%m-%d').date().month

def dzien_tygodnia_func(x):
    return datetime.strptime(x, '%Y-%m-%d').date().weekday()



df["Miesiąc_orzeczenia"] = df["Data_orzeczenia"].apply(miesiac_func)
df["Dzien_tygodnia_orzeczenia"] = df["Data_orzeczenia"].apply(dzien_tygodnia_func)
df

,Data_orzeczenia,Sąd,Sędziowie,Treść_wyniku,Prawomocność,Miesiąc_orzeczenia,Dzien_tygodnia_orzeczenia
0,2023-07-27,Wojewódzki Sąd Administracyjny we Wrocławiu,Dagmara Stankiewicz-Rajchman\nIwona Solatycka\...,0,0,7,3
1,2023-07-25,Wojewódzki Sąd Administracyjny w Gdańsku,Alicja Stępień /sprawozdawca/\nMałgorzata Gorz...,0,0,7,1
2,2023-07-19,Wojewódzki Sąd Administracyjny w Gliwicach,Borys Marasek\nDorota Kozłowska /przewodnicząc...,0,0,7,2
3,2023-07-12,Wojewódzki Sąd Administracyjny w Lublinie,Grzegorz Wałejko\nHalina Chitrosz-Roicka /prze...,0,0,7,2
4,2023-07-12,Wojewódzki Sąd Administracyjny w Gliwicach,Dorota Kozłowska\nMonika Krywow\nPaweł Kornack...,1,0,7,2
...,...,...,...,...,...,...,...
90,2023-05-16,Wojewódzki Sąd Administracyjny w Poznaniu,Katarzyna Wolna-Kubicka /przewodniczący/\nMich...,1,0,5,1
91,2023-05-16,Wojewódzki Sąd Administracyjny w Warszawie,Agnieszka Baran\nAgnieszka Sułkowska /sprawozd...,1,0,5,1
92,2023-05-16,Wojewódzki Sąd Administracyjny w Warszawie,Adrianna Elżbieta Grzymska-Truksa /sprawozdawc...,1,0,5,1
93,2023-05-16,Wojewódzki Sąd Administracyjny w Warszawie,Agnieszka Baran\nAgnieszka Sułkowska\nMarta Wa...,1,0,5,1
94,2023-05-16,Wojewódzki Sąd Administracyjny w Warszawie,Adrianna Elżbieta Grzymska-Truksa\nDariusz Cza...,1,0,5,1

In [182]:
df[['Miesiąc_orzeczenia', 'Treść_wyniku', 'Prawomocność']].groupby('Miesiąc_orzeczenia').mean().round(2)

                    Treść_wyniku  Prawomocność
Miesiąc_orzeczenia
1                           0.38          0.58
2                           0.48          0.47
3                           0.45          0.61
4                           0.45          0.39
5                           0.47          0.27
6                           0.40          0.53
7                           0.33          0.48
8                           0.55          0.48
9                           0.39          0.61
10                          0.38          0.65
11                          0.36          0.63
12                          0.51          0.54

In [183]:
df[['Dzien_tygodnia_orzeczenia', 'Treść_wyniku', 'Prawomocność']].groupby('Dzien_tygodnia_orzeczenia').mean().round(2)

                           Treść_wyniku  Prawomocność
Dzien_tygodnia_orzeczenia
0                                  0.55          0.27
1                                  0.43          0.54
2                                  0.39          0.57
3                                  0.46          0.49
4                                  0.37          0.48

In [184]:
df['Treść_wyniku'].value_counts()

Treść_wyniku
0    566
1    410
Name: count, dtype: int64

In [185]:
df['Dzien_tygodnia_orzeczenia'].value_counts()

Dzien_tygodnia_orzeczenia
1    330
2    309
3    203
4    112
0     22
Name: count, dtype: int64

In [ ]:
df.dtypes

In [178]:
df.loc[df['Treść_wyniku'] == "None",['Treść_wyniku']]

Empty DataFrame
Columns: [Treść_wyniku]
Index: []

In [174]:
df.loc[[763,]]

,Data_orzeczenia,Sąd,Sędziowie,Treść_wyniku,Prawomocność,Miesiąc_orzeczenia,Dzien_tygodnia_orzeczenia,name_0,name_1,name_2
763,2022-09-07,Wojewódzki Sąd Administracyjny w Warszawie,Adrianna Elżbieta Grzymska-Truksa\nDariusz Cza...,None,0,9,2,Adrianna Elżbieta Grzymska-Truksa,Dariusz Czarkowski,Marta Waksmundzka-Karasińska

In [179]:
df.iloc[[763,764],]

,Data_orzeczenia,Sąd,Sędziowie,Treść_wyniku,Prawomocność,Miesiąc_orzeczenia,Dzien_tygodnia_orzeczenia,name_0,name_1,name_2
763,2022-09-07,Wojewódzki Sąd Administracyjny w Warszawie,Adrianna Elżbieta Grzymska-Truksa\nDariusz Cza...,1,0,9,2,Adrianna Elżbieta Grzymska-Truksa,Dariusz Czarkowski,Marta Waksmundzka-Karasińska
764,2022-09-07,Wojewódzki Sąd Administracyjny w Warszawie,Adrianna Elżbieta Grzymska-Truksa\nDariusz Cza...,1,0,9,2,Adrianna Elżbieta Grzymska-Truksa,Dariusz Czarkowski,Marta Waksmundzka-Karasińska

In [114]:
df[['Sędziowie']]

                                            Sędziowie
0   Dagmara Stankiewicz-Rajchman\nIwona Solatycka\...
1   Alicja Stępień /sprawozdawca/\nMałgorzata Gorz...
2   Borys Marasek\nDorota Kozłowska /przewodnicząc...
3   Grzegorz Wałejko\nHalina Chitrosz-Roicka /prze...
4   Dorota Kozłowska\nMonika Krywow\nPaweł Kornack...
..                                                ...
90  Katarzyna Wolna-Kubicka /przewodniczący/\nMich...
91  Agnieszka Baran\nAgnieszka Sułkowska /sprawozd...
92  Adrianna Elżbieta Grzymska-Truksa /sprawozdawc...
93  Agnieszka Baran\nAgnieszka Sułkowska\nMarta Wa...
94  Adrianna Elżbieta Grzymska-Truksa\nDariusz Cza...

[95 rows x 1 columns]

In [128]:
df = df.join(df['Sędziowie'].str.split('\n',expand=True).add_prefix('name_'))
df

,Data_orzeczenia,Sąd,Sędziowie,Treść_wyniku,Prawomocność,Miesiąc_orzeczenia,Dzien_tygodnia_orzeczenia,name_0,name_1,name_2
0,2023-07-27,Wojewódzki Sąd Administracyjny we Wrocławiu,Dagmara Stankiewicz-Rajchman\nIwona Solatycka\...,0,0,7,3,Dagmara Stankiewicz-Rajchman,Iwona Solatycka,Tadeusz Haberka /przewodniczący sprawozdawca/
1,2023-07-25,Wojewódzki Sąd Administracyjny w Gdańsku,Alicja Stępień /sprawozdawca/\nMałgorzata Gorz...,0,0,7,1,Alicja Stępień /sprawozdawca/,Małgorzata Gorzeń /przewodniczący/,Marek Kraus
2,2023-07-19,Wojewódzki Sąd Administracyjny w Gliwicach,Borys Marasek\nDorota Kozłowska /przewodnicząc...,0,0,7,2,Borys Marasek,Dorota Kozłowska /przewodniczący/,Monika Krywow /sprawozdawca/
3,2023-07-12,Wojewódzki Sąd Administracyjny w Lublinie,Grzegorz Wałejko\nHalina Chitrosz-Roicka /prze...,0,0,7,2,Grzegorz Wałejko,Halina Chitrosz-Roicka /przewodniczący sprawoz...,Monika Kazubińska-Kręcisz
4,2023-07-12,Wojewódzki Sąd Administracyjny w Gliwicach,Dorota Kozłowska\nMonika Krywow\nPaweł Kornack...,1,0,7,2,Dorota Kozłowska,Monika Krywow,Paweł Kornacki /przewodniczący sprawozdawca/
...,...,...,...,...,...,...,...,...,...,...
90,2023-05-16,Wojewódzki Sąd Administracyjny w Poznaniu,Katarzyna Wolna-Kubicka /przewodniczący/\nMich...,1,0,5,1,Katarzyna Wolna-Kubicka /przewodniczący/,Michał Ilski,Waldemar Inerowicz /sprawozdawca/
91,2023-05-16,Wojewódzki Sąd Administracyjny w Warszawie,Agnieszka Baran\nAgnieszka Sułkowska /sprawozd...,1,0,5,1,Agnieszka Baran,Agnieszka Sułkowska /sprawozdawca/,Marta Waksmundzka-Karasińska /przewodniczący/
92,2023-05-16,Wojewódzki Sąd Administracyjny w Warszawie,Adrianna Elżbieta Grzymska-Truksa /sprawozdawc...,1,0,5,1,Adrianna Elżbieta Grzymska-Truksa /sprawozdawca/,Dariusz Czarkowski,Matylda Arnold-Rogiewicz /przewodniczący/
93,2023-05-16,Wojewódzki Sąd Administracyjny w Warszawie,Agnieszka Baran\nAgnieszka Sułkowska\nMarta Wa...,1,0,5,1,Agnieszka Baran,Agnieszka Sułkowska,Marta Waksmundzka-Karasińska /przewodniczący s...
94,2023-05-16,Wojewódzki Sąd Administracyjny w Warszawie,Adrianna Elżbieta Grzymska-Truksa\nDariusz Cza...,1,0,5,1,Adrianna Elżbieta Grzymska-Truksa,Dariusz Czarkowski,Matylda Arnold-Rogiewicz /przewodniczący spraw...

In [131]:
def sędzia_func(x):
    if isinstance(x,str):
        return re.split(" /", x)[0]""
    else:
        return "None"

df["name_0"] = df["name_0"].apply(sędzia_func)
df["name_1"] = df["name_1"].apply(sędzia_func)
df["name_2"] = df["name_2"].apply(sędzia_func)
df

,Data_orzeczenia,Sąd,Sędziowie,Treść_wyniku,Prawomocność,Miesiąc_orzeczenia,Dzien_tygodnia_orzeczenia,name_0,name_1,name_2
0,2023-07-27,Wojewódzki Sąd Administracyjny we Wrocławiu,Dagmara Stankiewicz-Rajchman\nIwona Solatycka\...,0,0,7,3,Dagmara Stankiewicz-Rajchman,Iwona Solatycka,Tadeusz Haberka
1,2023-07-25,Wojewódzki Sąd Administracyjny w Gdańsku,Alicja Stępień /sprawozdawca/\nMałgorzata Gorz...,0,0,7,1,Alicja Stępień,Małgorzata Gorzeń,Marek Kraus
2,2023-07-19,Wojewódzki Sąd Administracyjny w Gliwicach,Borys Marasek\nDorota Kozłowska /przewodnicząc...,0,0,7,2,Borys Marasek,Dorota Kozłowska,Monika Krywow
3,2023-07-12,Wojewódzki Sąd Administracyjny w Lublinie,Grzegorz Wałejko\nHalina Chitrosz-Roicka /prze...,0,0,7,2,Grzegorz Wałejko,Halina Chitrosz-Roicka,Monika Kazubińska-Kręcisz
4,2023-07-12,Wojewódzki Sąd Administracyjny w Gliwicach,Dorota Kozłowska\nMonika Krywow\nPaweł Kornack...,1,0,7,2,Dorota Kozłowska,Monika Krywow,Paweł Kornacki
...,...,...,...,...,...,...,...,...,...,...
90,2023-05-16,Wojewódzki Sąd Administracyjny w Poznaniu,Katarzyna Wolna-Kubicka /przewodniczący/\nMich...,1,0,5,1,Katarzyna Wolna-Kubicka,Michał Ilski,Waldemar Inerowicz
91,2023-05-16,Wojewódzki Sąd Administracyjny w Warszawie,Agnieszka Baran\nAgnieszka Sułkowska /sprawozd...,1,0,5,1,Agnieszka Baran,Agnieszka Sułkowska,Marta Waksmundzka-Karasińska
92,2023-05-16,Wojewódzki Sąd Administracyjny w Warszawie,Adrianna Elżbieta Grzymska-Truksa /sprawozdawc...,1,0,5,1,Adrianna Elżbieta Grzymska-Truksa,Dariusz Czarkowski,Matylda Arnold-Rogiewicz
93,2023-05-16,Wojewódzki Sąd Administracyjny w Warszawie,Agnieszka Baran\nAgnieszka Sułkowska\nMarta Wa...,1,0,5,1,Agnieszka Baran,Agnieszka Sułkowska,Marta Waksmundzka-Karasińska
94,2023-05-16,Wojewódzki Sąd Administracyjny w Warszawie,Adrianna Elżbieta Grzymska-Truksa\nDariusz Cza...,1,0,5,1,Adrianna Elżbieta Grzymska-Truksa,Dariusz Czarkowski,Matylda Arnold-Rogiewicz

In [ ]:
df[['name_0', 'Treść_wyniku', 'Prawomocność']].groupby('name_0').mean().round(2)

In [ ]:
df[['name_1', 'Treść_wyniku', 'Prawomocność']].groupby('name_1').mean().round(2)

In [268]:
df['name_0'].value_counts()

name_0
Aleksandra Wrzesińska- Nowacka       101
Agnieszka Olesińska                   70
Antoni Hanusz                         64
Adrianna Elżbieta Grzymska-Truksa     44
Agnieszka Baran                       43
                                    ...
Joanna Zdzienicka-Wiśniewska           1
Marek Kraus                            1
Paweł Kowalski                         1
Joanna Grzegorczyk-Drozda              1
Grzegorz Potiopa                       1
Name: count, Length: 106, dtype: int64

In [269]:
df['name_1'].value_counts()

name_1
None                       107
Antoni Hanusz               60
Jerzy Płusa                 58
Dariusz Czarkowski          41
Anna Dumas                  33
                          ...
Marek Wroczyński             1
Anna Sokołowska              1
Katarzyna Stuła-Marcela      1
Łukasz Cieślak               1
Krzysztof Kandut             1
Name: count, Length: 105, dtype: int64

In [194]:
df['name_2'].value_counts()

name_2
None                         107
Tomasz Kolanowski             95
Maciej Jaśniewicz             48
Zbigniew Romała               36
Małgorzata Wolf- Kalamala     35
                            ...
Paweł Dąbek                    1
Marzena Kowalewska             1
Cezary Koziński                1
Grzegorz Potiopa               1
Karol Pawlicki                 1
Name: count, Length: 92, dtype: int64

In [189]:
df['name_0'].nunique()

106

In [190]:
df['name_1'].nunique()

105

In [191]:
df['name_2'].nunique()

92

In [270]:
def get_unique_num_of_judges():
    n = len(set(df['name_0'].tolist() + df['name_1'].tolist() + df['name_2'].tolist()))
    return n

get_unique_num_of_judges()

157

In [279]:
df.head()

,Data_orzeczenia,Sąd,Sędziowie,Treść_wyniku,Prawomocność,Miesiąc_orzeczenia,Dzien_tygodnia_orzeczenia,name_0,name_1,name_2
0,2023-07-27,Wojewódzki Sąd Administracyjny we Wrocławiu,Dagmara Stankiewicz-Rajchman\nIwona Solatycka\...,0,0,7,3,Dagmara Stankiewicz-Rajchman,Iwona Solatycka,Tadeusz Haberka
1,2023-07-26,Wojewódzki Sąd Administracyjny w Lublinie,Grzegorz Wałejko\nHalina Chitrosz-Roicka /prze...,0,0,7,2,Grzegorz Wałejko,Halina Chitrosz-Roicka,Monika Kazubińska-Kręcisz
2,2023-07-25,Wojewódzki Sąd Administracyjny w Gdańsku,Alicja Stępień /sprawozdawca/\nMałgorzata Gorz...,0,0,7,1,Alicja Stępień,Małgorzata Gorzeń,Marek Kraus
3,2023-07-24,Wojewódzki Sąd Administracyjny w Gliwicach,Beata Machcińska /przewodniczący sprawozdawca/,1,0,7,0,Beata Machcińska,None,None
4,2023-07-19,Wojewódzki Sąd Administracyjny w Gliwicach,Borys Marasek\nDorota Kozłowska /przewodnicząc...,0,0,7,2,Borys Marasek,Dorota Kozłowska,Monika Krywow

In [293]:
dum0 = pd.get_dummies(df['name_0'])
dum1 = pd.get_dummies(df['name_1'])
dum2 = pd.get_dummies(df['name_2'])

In [294]:
dum0

,Adam Jutrzenka-Trzebiatowski,Adrianna Elżbieta Grzymska-Truksa,Agata Ćwik-Bury,Agnieszka Banach,Agnieszka Baran,Agnieszka Gortych-Ratajczyk,Agnieszka Kosowska,Agnieszka Krawczyk,Agnieszka Olesińska,Agnieszka Sułkowska,...,Paweł Kowalski,Piotr Kieres,Piotr Popek,Robert Talaga,Stefan Babiarz,Tomasz Smoleń,Waldemar Inerowicz,Waldemar Michaldo,Wiesław Kuśnierz,Łukasz Cieślak
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
971,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
972,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
973,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
974,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
975,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [239]:
out0 = pd.merge(df, dum0, left_index=True, right_index=True)
out1 = pd.merge(out0, dum1, left_index=True, right_index=True)
out2 = pd.merge(out1, dum2, left_index=True, right_index=True)

In [289]:
df.shape

(976, 167)

In [288]:
df.head()

,Data_orzeczenia,Sąd,Sędziowie,Treść_wyniku,Prawomocność,Miesiąc_orzeczenia,Dzien_tygodnia_orzeczenia,name_0,name_1,name_2,...,Adrianna Elżbieta Grzymska-Truksa,Michał Niedźwiedź,Anna Rotter,Elżbieta Dziel,Wiesława Achrymowicz,Konrad Aromiński,Jarosław Wiśniewski,Paweł Janicki,Jacek Boratyn,Nadzieja Karczmarczyk-Gawęcka
0,2023-07-27,Wojewódzki Sąd Administracyjny we Wrocławiu,Dagmara Stankiewicz-Rajchman\nIwona Solatycka\...,0,0,7,3,Dagmara Stankiewicz-Rajchman,Iwona Solatycka,Tadeusz Haberka,...,False,False,False,False,False,False,False,False,False,False
1,2023-07-26,Wojewódzki Sąd Administracyjny w Lublinie,Grzegorz Wałejko\nHalina Chitrosz-Roicka /prze...,0,0,7,2,Grzegorz Wałejko,Halina Chitrosz-Roicka,Monika Kazubińska-Kręcisz,...,True,False,False,False,False,False,False,False,False,False
2,2023-07-25,Wojewódzki Sąd Administracyjny w Gdańsku,Alicja Stępień /sprawozdawca/\nMałgorzata Gorz...,0,0,7,1,Alicja Stępień,Małgorzata Gorzeń,Marek Kraus,...,False,False,False,False,False,False,False,False,False,False
3,2023-07-24,Wojewódzki Sąd Administracyjny w Gliwicach,Beata Machcińska /przewodniczący sprawozdawca/,1,0,7,0,Beata Machcińska,None,None,...,False,False,False,False,False,False,False,False,False,False
4,2023-07-19,Wojewódzki Sąd Administracyjny w Gliwicach,Borys Marasek\nDorota Kozłowska /przewodnicząc...,0,0,7,2,Borys Marasek,Dorota Kozłowska,Monika Krywow,...,False,False,False,False,False,False,False,False,False,False

In [295]:
def get_names():
    names = list(dum0.columns.values) + list(dum1.columns.values) + list(dum2.columns.values)
    return list(set(names))

In [297]:
df.head()

,Data_orzeczenia,Sąd,Sędziowie,Treść_wyniku,Prawomocność,Miesiąc_orzeczenia,Dzien_tygodnia_orzeczenia,name_0,name_1,name_2,...,Adrianna Elżbieta Grzymska-Truksa,Michał Niedźwiedź,Anna Rotter,Elżbieta Dziel,Wiesława Achrymowicz,Konrad Aromiński,Jarosław Wiśniewski,Paweł Janicki,Jacek Boratyn,Nadzieja Karczmarczyk-Gawęcka
0,2023-07-27,Wojewódzki Sąd Administracyjny we Wrocławiu,Dagmara Stankiewicz-Rajchman\nIwona Solatycka\...,0,0,7,3,Dagmara Stankiewicz-Rajchman,Iwona Solatycka,Tadeusz Haberka,...,False,False,False,False,False,False,False,False,False,False
1,2023-07-26,Wojewódzki Sąd Administracyjny w Lublinie,Grzegorz Wałejko\nHalina Chitrosz-Roicka /prze...,0,0,7,2,Grzegorz Wałejko,Halina Chitrosz-Roicka,Monika Kazubińska-Kręcisz,...,True,False,False,False,False,False,False,False,False,False
2,2023-07-25,Wojewódzki Sąd Administracyjny w Gdańsku,Alicja Stępień /sprawozdawca/\nMałgorzata Gorz...,0,0,7,1,Alicja Stępień,Małgorzata Gorzeń,Marek Kraus,...,False,False,False,False,False,False,False,False,False,False
3,2023-07-24,Wojewódzki Sąd Administracyjny w Gliwicach,Beata Machcińska /przewodniczący sprawozdawca/,1,0,7,0,Beata Machcińska,None,None,...,False,False,False,False,False,False,False,False,False,False
4,2023-07-19,Wojewódzki Sąd Administracyjny w Gliwicach,Borys Marasek\nDorota Kozłowska /przewodnicząc...,0,0,7,2,Borys Marasek,Dorota Kozłowska,Monika Krywow,...,False,False,False,False,False,False,False,False,False,False

In [296]:
for col_name in get_names():
    if col_name in dum0:
        status0 = dum0.loc[:, col_name]
    if col_name in dum1:
        status1 = dum1.loc[:, col_name]
    if col_name in dum2:
        status2 = dum2.loc[:, col_name]
    

    new_value = status0 | status1 | status2
    
    df[col_name] = new_value

/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value
/var/folders/07/q76lgth93wd8856q91ggr4fw0000gn/T/ipykernel_7183/2743019384.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name] = new_value

In [298]:
out[["Aleksandra Wrzesińska- Nowacka", 'Treść_wyniku', 'Prawomocność']].groupby("Aleksandra Wrzesińska- Nowacka").mean().round(2)

                                Treść_wyniku  Prawomocność
Aleksandra Wrzesińska- Nowacka
False                                   0.44          0.47
True                                    0.29          1.00

In [258]:
out2.filter(regex='^T')

,Treść_wyniku,Tomasz Smoleń_x,Tomasz Kolanowski_x,Tomasz Wójcik_x,Tomasz Zborzyński_x,Tadeusz Haberka,Tomasz Furmanek,Tomasz Grzybowski,Tomasz Judecki,Tomasz Kolanowski_y,Tomasz Smoleń_y,Tomasz Wójcik_y,Tomasz Zborzyński_y
0,0,False,False,False,False,True,False,False,False,False,False,False,False
1,0,False,False,False,False,False,False,False,False,False,False,False,False
2,0,False,False,False,False,False,False,False,False,False,False,False,False
3,1,False,False,False,False,False,False,False,False,False,False,False,False
4,0,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
971,0,False,False,False,False,False,False,False,False,False,False,False,False
972,0,False,False,False,False,False,False,False,False,False,False,False,False
973,0,False,False,False,False,False,False,False,False,False,False,False,False
974,0,False,False,False,False,False,False,False,False,False,False,False,False
975,0,False,False,False,False,False,False,False,False,False,False,False,False

In [299]:
df.drop(columns=['Sędziowie', 'name_0', 'name_1', 'name_2'])

,Data_orzeczenia,Sąd,Treść_wyniku,Prawomocność,Miesiąc_orzeczenia,Dzien_tygodnia_orzeczenia,Dariusz Marian Zalewski,Jerzy Płusa,Ewa Cisowska-Sakrajda,Katarzyna Nikodem,...,Adrianna Elżbieta Grzymska-Truksa,Michał Niedźwiedź,Anna Rotter,Elżbieta Dziel,Wiesława Achrymowicz,Konrad Aromiński,Jarosław Wiśniewski,Paweł Janicki,Jacek Boratyn,Nadzieja Karczmarczyk-Gawęcka
0,2023-07-27,Wojewódzki Sąd Administracyjny we Wrocławiu,0,0,7,3,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2023-07-26,Wojewódzki Sąd Administracyjny w Lublinie,0,0,7,2,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
2,2023-07-25,Wojewódzki Sąd Administracyjny w Gdańsku,0,0,7,1,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,2023-07-24,Wojewódzki Sąd Administracyjny w Gliwicach,1,0,7,0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,2023-07-19,Wojewódzki Sąd Administracyjny w Gliwicach,0,0,7,2,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
971,2022-06-07,Wojewódzki Sąd Administracyjny w Poznaniu,0,0,6,1,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
972,2022-06-07,Wojewódzki Sąd Administracyjny w Poznaniu,0,0,6,1,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
973,2022-06-07,Wojewódzki Sąd Administracyjny w Poznaniu,0,0,6,1,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
974,2022-06-07,Wojewódzki Sąd Administracyjny w Poznaniu,0,0,6,1,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
975,2022-06-07,Wojewódzki Sąd Administracyjny w Poznaniu,0,0,6,1,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [306]:
wyniki_sądów = df[["Sąd", "Treść_wyniku"]].groupby("Sąd").mean().round(2).sort_values('Treść_wyniku', ascending=False)
wyniki_sądów

                                                 Treść_wyniku
Sąd
Wojewódzki Sąd Administracyjny w Opolu                   0.77
Wojewódzki Sąd Administracyjny w Krakowie                0.70
Wojewódzki Sąd Administracyjny w Gliwicach               0.68
Wojewódzki Sąd Administracyjny w Rzeszowie               0.68
Wojewódzki Sąd Administracyjny we Wrocławiu              0.67
Wojewódzki Sąd Administracyjny w Olsztynie               0.67
Wojewódzki Sąd Administracyjny w Poznaniu                0.64
Wojewódzki Sąd Administracyjny w Łodzi                   0.57
Wojewódzki Sąd Administracyjny w Warszawie               0.57
Wojewódzki Sąd Administracyjny w Szczecinie              0.56
Wojewódzki Sąd Administracyjny w Gdańsku                 0.52
Wojewódzki Sąd Administracyjny w Gorzowie Wlkp.          0.50
Wojewódzki Sąd Administracyjny w Kielcach                0.40
Wojewódzki Sąd Administracyjny w Bydgoszczy              0.35
Wojewódzki Sąd Administracyjny w Białymstoku             0.35
Wojewódzki Sąd Administracyjny w Lublinie                0.27
Naczelny Sąd Administracyjny                             0.21

In [310]:
sądy_count = df[["Sąd"]].value_counts()
sądy_count

Sąd
Naczelny Sąd Administracyjny                       397
Wojewódzki Sąd Administracyjny w Warszawie         162
Wojewódzki Sąd Administracyjny w Poznaniu           75
Wojewódzki Sąd Administracyjny w Lublinie           49
Wojewódzki Sąd Administracyjny we Wrocławiu         48
Wojewódzki Sąd Administracyjny w Gliwicach          40
Wojewódzki Sąd Administracyjny w Łodzi              37
Wojewódzki Sąd Administracyjny w Krakowie           30
Wojewódzki Sąd Administracyjny w Gdańsku            27
Wojewódzki Sąd Administracyjny w Rzeszowie          22
Wojewódzki Sąd Administracyjny w Bydgoszczy         20
Wojewódzki Sąd Administracyjny w Białymstoku        17
Wojewódzki Sąd Administracyjny w Gorzowie Wlkp.     16
Wojewódzki Sąd Administracyjny w Opolu              13
Wojewódzki Sąd Administracyjny w Olsztynie           9
Wojewódzki Sąd Administracyjny w Szczecinie          9
Wojewódzki Sąd Administracyjny w Kielcach            5
Name: count, dtype: int64

In [313]:
xd = pd.merge(wyniki_sądów, sądy_count, on='Sąd')
xd

                                                 Treść_wyniku  count
Sąd
Wojewódzki Sąd Administracyjny w Opolu                   0.77     13
Wojewódzki Sąd Administracyjny w Krakowie                0.70     30
Wojewódzki Sąd Administracyjny w Gliwicach               0.68     40
Wojewódzki Sąd Administracyjny w Rzeszowie               0.68     22
Wojewódzki Sąd Administracyjny we Wrocławiu              0.67     48
Wojewódzki Sąd Administracyjny w Olsztynie               0.67      9
Wojewódzki Sąd Administracyjny w Poznaniu                0.64     75
Wojewódzki Sąd Administracyjny w Łodzi                   0.57     37
Wojewódzki Sąd Administracyjny w Warszawie               0.57    162
Wojewódzki Sąd Administracyjny w Szczecinie              0.56      9
Wojewódzki Sąd Administracyjny w Gdańsku                 0.52     27
Wojewódzki Sąd Administracyjny w Gorzowie Wlkp.          0.50     16
Wojewódzki Sąd Administracyjny w Kielcach                0.40      5
Wojewódzki Sąd Administracyjny w Bydgoszczy              0.35     20
Wojewódzki Sąd Administracyjny w Białymstoku             0.35     17
Wojewódzki Sąd Administracyjny w Lublinie                0.27     49
Naczelny Sąd Administracyjny                             0.21    397

In [315]:
xd[xd['count'] >= 40]

                                             Treść_wyniku  count
Sąd
Wojewódzki Sąd Administracyjny w Gliwicach           0.68     40
Wojewódzki Sąd Administracyjny we Wrocławiu          0.67     48
Wojewódzki Sąd Administracyjny w Poznaniu            0.64     75
Wojewódzki Sąd Administracyjny w Warszawie           0.57    162
Wojewódzki Sąd Administracyjny w Lublinie            0.27     49
Naczelny Sąd Administracyjny                         0.21    397